name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: cd adt && go build -v ./... && cd .. && cd mut && go build -v ./... && cd ..

      - name: Test
        run: cd adt && go test -v ./... && cd .. && cd mut && go test -v ./... && cd ..
